set -x
ENGINE=${1:-vllm}

export SWANLAB_API_KEY="5fi2cgzDNC4ccLyceA7ni"           # 设置在线跟踪模式API
export SWANLAB_LOG_DIR="/data/wangnn/repos/verl/debiasing/log"  # 设置本地日志存储路径
export SWANLAB_MODE="disabled"    # 包含四种模式：cloud云端跟踪模式（默认）、cloud-only仅云端跟踪本地不保存文件、local本地跟踪模式、disabled完全不记录用于debug

export CUDA_VISIBLE_DEVICES=0,1,2,3

PYTHONUNBUFFRED=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=/data/wangnn/repos/verl/debiasing/data/train.parquet \
    data.val_files=/data/wangnn/repos/verl/debiasing/data/test.parquet \
    data.train_batch_size=16 \
    data.max_prompt_length=1024 \
    data.max_response_length=128 \
    data.filter_overlong_prompts=True \
    data.return_raw_chat=True \
    data.truncation='error' \
    data.image_key=images \
    actor_rollout_ref.model.path=/data/wangnn/models/Qwen2.5-VL-3B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=false \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=false \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=sglang \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.0 8\
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.nccl_timeout=36000 \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.rollout.n=2 \
    actor_rollout_ref.rollout.multi_turn.enable=True\
    actor_rollout_ref.rollout.multi_turn.interaction_config_path=/data/wangnn/repos/verl/debiasing/waterbird_interaction.yaml \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    custom_reward_function.path=/data/wangnn/repos/verl/debiasing/waterbird_reward_func.py \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console","swanlab"]' \
    trainer.project_name='debiasing_v1_t2' \
    trainer.experiment_name='qwen2_5_vl_3b_debiasing_v1_t1' \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=1 \
    trainer.total_epochs=15\
    trainer.val_before_train=False $@
